[workspace]
members = [
    "firestorm",
    "firestorm-enabled",
    "firestorm-core",
]

[patch.crates-io]
firestorm-core = { path = "firestorm-core" }
firestorm-enabled = { path = "firestorm-enabled" }