[package]
name = "firestorm"
version = "0.3.0"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A low overhead intrusive flamegraph profiler."

[features]
enabled = ["inferno", "firestorm-core"]

[dependencies]
inferno = { version="0.10.0", optional=true }
firestorm-core = { version="0.1.0", optional=true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "soak_bench"
harness = false