[package]
name = "firestorm-core"
version = "0.1.1"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Internals for firestorm"

[features]
system_time = []
cpu_time = ["amd64_timer"]

[dependencies]
amd64_timer = { version="1.3.0", optional=true }
